# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramen Weather
email: david@ramenweather.com
description: > # this means to ignore newlines until "baseurl:"
  Ramen Weather is soul food, to be enjoyed however you like.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ramenweather.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  RamenWeather

# Build settings
markdown: kramdown

# Theme
remote_theme: "mmistakes/so-simple-theme"
